{"name": "Delete file", "status": "broken", "statusDetails": {"message": "NameError: name 'assert_internal_error_response' is not defined", "trace": "self = <testdata.tests.files.test_files.TestFiles object at 0x000002114BEEE810>\nfiles_client = <clients.files.files_client.FilesClient object at 0x000002114BFE2F30>\nfunction_files = FileFixture(request=CreateFileRequestSchema(filename='9846d3be-f629-4f59-968b-f2a339f93676.png', directory='tests', up...s/9846d3be-f629-4f59-968b-f2a339f93676.png'), filename='9846d3be-f629-4f59-968b-f2a339f93676.png', directory='tests')))\n\n    @allure.tag(AllureTag.DELETE_ENTITY)\n    @allure.title(\"Delete file\")\n    @allure.story(AllureStory.DELETE_ENTITY)\n    @allure.severity(Severity.NORMAL)\n    @allure.sub_suite(AllureStory.DELETE_ENTITY)\n    def test_delete_file(self, files_client: FilesClient, function_files: FileFixture):\n        delete_response = files_client.delete_file_api(function_files.response.file.id)\n        assert_status_code(delete_response.status_code, HTTPStatus.OK)\n    \n        get_response = files_client.get_file_api(function_files.response.file.id)\n        get_response_data = InternalErrorResponseSchema.model_validate_json(get_response.text)\n    \n        assert_status_code(get_response.status_code, HTTPStatus.NOT_FOUND)\n>       assert_file_not_found_response(get_response_data)\n\ntestdata\\tests\\files\\test_files.py:107: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nactual = InternalErrorResponseSchema(details='File not found')\n\n    @allure.step(\"Check file not found response\")\n    def assert_file_not_found_response(actual: InternalErrorResponseSchema):\n        \"\"\"\n        Функция для проверки ошибки, если файл не найден на сервере.\n    \n        :param actual: Фактический ответ.\n        :raises AssertionError: Если фактический ответ не соответствует ошибке \"File not found\"\n        \"\"\"\n        logger.info(\"Check file not found response\")\n    \n        expected = InternalErrorResponseSchema(detail=\"File not found\")\n>       assert_internal_error_response(actual, expected)\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nE       NameError: name 'assert_internal_error_response' is not defined\n\ntools\\assertions\\files.py:119: NameError"}, "steps": [{"name": "Delete file by id 'afce5262-84aa-42e8-bf40-9f0a3f22e06e'", "status": "passed", "steps": [{"name": "Make DELETE  request to '/api/v1/files/afce5262-84aa-42e8-bf40-9f0a3f22e06e'", "status": "passed", "attachments": [{"name": "cURL command", "source": "2623b10a-825e-49ae-92f8-d7c571889b9c-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "url", "value": "'/api/v1/files/afce5262-84aa-42e8-bf40-9f0a3f22e06e'"}], "start": 1755782144169, "stop": 1755782144587}], "parameters": [{"name": "file_id", "value": "'afce5262-84aa-42e8-bf40-9f0a3f22e06e'"}], "start": 1755782144169, "stop": 1755782144587}, {"name": "Check that response status code equals to <HTTPStatus.OK: 200>", "status": "passed", "parameters": [{"name": "actual", "value": "200"}, {"name": "expected", "value": "<HTTPStatus.OK: 200>"}], "start": 1755782144587, "stop": 1755782144592}, {"name": "Get file by id 'afce5262-84aa-42e8-bf40-9f0a3f22e06e'", "status": "passed", "steps": [{"name": "Make GET request to '/api/v1/files/afce5262-84aa-42e8-bf40-9f0a3f22e06e'", "status": "passed", "attachments": [{"name": "cURL command", "source": "a00e8347-cee9-41b6-9852-27ddbb87aa93-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "url", "value": "'/api/v1/files/afce5262-84aa-42e8-bf40-9f0a3f22e06e'"}, {"name": "params", "value": "None"}], "start": 1755782144592, "stop": 1755782144637}], "parameters": [{"name": "file_id", "value": "'afce5262-84aa-42e8-bf40-9f0a3f22e06e'"}], "start": 1755782144592, "stop": 1755782144637}, {"name": "Check that response status code equals to <HTTPStatus.NOT_FOUND: 404>", "status": "passed", "parameters": [{"name": "actual", "value": "404"}, {"name": "expected", "value": "<HTTPStatus.NOT_FOUND: 404>"}], "start": 1755782144637, "stop": 1755782144637}, {"name": "Check file not found response", "status": "broken", "statusDetails": {"message": "NameError: name 'assert_internal_error_response' is not defined\n", "trace": "  File \"C:\\Users\\user\\PycharmProjects\\autotests-api\\.venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 202, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Users\\user\\PycharmProjects\\autotests-api\\tools\\assertions\\files.py\", line 119, in assert_file_not_found_response\n    assert_internal_error_response(actual, expected)\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n"}, "parameters": [{"name": "actual", "value": "InternalErrorResponseSchema(details='File not found')"}], "start": 1755782144637, "stop": 1755782144637}], "attachments": [{"name": "log", "source": "c1bf2a46-9e28-4b63-a6b6-88e36042e66c-attachment.txt", "type": "text/plain"}], "start": 1755782144169, "stop": 1755782144640, "uuid": "5b9d1add-ecf8-4e2b-92e2-e46b32e41755", "historyId": "4b0d11c3f49d25bb34e5901ab501ebe4", "testCaseId": "4b0d11c3f49d25bb34e5901ab501ebe4", "fullName": "testdata.tests.files.test_files.TestFiles#test_delete_file", "labels": [{"name": "story", "value": "Delete entity"}, {"name": "subSuite", "value": "Delete entity"}, {"name": "epic", "value": "LMS service"}, {"name": "suite", "value": "Files"}, {"name": "tag", "value": "REGRESSION"}, {"name": "severity", "value": "normal"}, {"name": "tag", "value": "FILES"}, {"name": "parentSuite", "value": "LMS service"}, {"name": "tag", "value": "DELETE_ENTITY"}, {"name": "feature", "value": "Files"}, {"name": "tag", "value": "regression"}, {"name": "tag", "value": "files"}, {"name": "host", "value": "WIN-D6J80KEQ9S3"}, {"name": "thread", "value": "2264-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testdata.tests.files.test_files"}], "titlePath": ["testdata", "tests", "files", "test_files.py", "TestFiles"]}